project:
  type: website

website:
  title: "Mysiloglou Dimitrios"
  favicon: favicon.ico
  twitter-card: true

  navbar:
    background: light
    title: false
    logo-alt: "Mysiloglou Dimitrios"
    logo: images/logo.png
    logo-href: https://jimmysiloglou.eu.pythonanywhere.com
    
    left:
      - text: "Blog"
        href: blog.qmd
      - text: "Portfolio"
        href: portfolio.qmd
      - text: "My Journey"
        href: https://jimmysiloglou.eu.pythonanywhere.com/my_journey/
      - text: "Contact"
        href: https://jimmysiloglou.eu.pythonanywhere.com/contact/
      



  page-footer:
    left: "Â© 2022 Copyright: Mysiloglou Dimitrios"
    right:
      - icon: github
        href: https://github.com/JimMysiloglou
      - icon: linkedin
        href: https://www.linkedin.com/in/jimmysiloglou/
      - icon: twitter
        href: https://twitter.com/JimMysiloglou
      - icon: facebook
        href: https://www.facebook.com/jim.misi/
    border: false

format:
  html:
    theme:
      - materia
      - custom.scss



